#version: "3.9"

services:

  ms-users:
    build: ./ms-users
    container_name: ms-users
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - ticket-network

#  ms-tickets:
#    build: ./ms-tickets
#    container_name: ms-tickets
#    ports:
#      - "8082:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#    networks:
#      - ticket-network
#
#  ms-gateway-auth:
#    build: ./ms-gateway-auth
#    container_name: ms-gateway-auth
#    ports:
#      - "3000:3000"
#    networks:
#      - ticket-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ticket-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Mensajería
      - "15672:15672"   # Consola web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ticket-network

networks:
  ticket-network:
    driver: bridge
