server:
  port: 8082

spring:

  datasource:
    url: jdbc:h2:mem:ticketsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  level:
    org.springframework: INFO
    com.tickets.tickets: DEBUG
    org.springframework.boot.context.config: DEBUG

jwt:
  secret: ${JWT_SECRET:supersecretoseguro123}